version: '3.4'

services:
  phaser3projecttemplate:
    image: phaser3projecttemplate
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
